# Generated by Django 2.1 on 2018-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=50)),
                ('banner_description', models.TextField()),
                ('banner_background_image', models.FileField(upload_to='banner/')),
                ('banner_image', models.FileField(upload_to='banner/')),
                ('banner_active', models.BooleanField(default=True)),
            ],
        ),
    ]
