# Generated by Django 2.1 on 2018-08-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerModels',
            new_name='BannerModel',
        ),
    ]
