# Generated by Django 2.1 on 2018-08-31 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180831_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(max_length=50)),
                ('detail_description', models.TextField()),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='details/images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_Description', models.TextField()),
                ('product_available', models.PositiveIntegerField(default=1)),
                ('product_price', models.FloatField()),
                ('product_discount', models.FloatField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_detail', models.ManyToManyField(to='products.ProductDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='banner_background_image',
            field=models.FileField(upload_to='banner/bgimage'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='banner_image',
            field=models.FileField(upload_to='banner/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'])]),
        ),
    ]
