# Generated by Django 2.1 on 2018-08-31 13:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('products', '0003_auto_20180831_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetailsModel',
        ),
    ]
