# Generated by Django 2.1 on 2018-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ratingandreviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_review',
            field=models.ManyToManyField(to='products.RatingAndReviewModel'),
        ),
    ]
