# Generated by Django 2.1 on 2018-09-03 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productmodel_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandreviewmodel',
            name='rating_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 9, 49, 15, 759722, tzinfo=utc)),
        ),
    ]
