# Generated by Django 2.1 on 2018-09-03 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180903_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandreviewmodel',
            name='rating_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
