# Generated by Django 2.1 on 2018-09-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180903_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CategoriesModel')),
            ],
        ),
    ]
