# Generated by Django 2.1 on 2018-09-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180903_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CategoriesModel'),
        ),
    ]
