# Generated by Django 2.1 on 2018-09-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productmodel_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='category_subcategory',
            new_name='category_parent',
        ),
    ]
