# Generated by Django 2.1 on 2018-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180903_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_review',
            field=models.ManyToManyField(blank=True, null=True, to='products.RatingAndReviewModel'),
        ),
    ]
