# Generated by Django 2.1 on 2018-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180903_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_detail',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductDetailsModel'),
        ),
    ]
