# Generated by Django 2.1 on 2018-09-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180903_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_detail',
            field=models.ManyToManyField(blank=True, to='products.ProductDetailsModel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_review',
            field=models.ManyToManyField(blank=True, to='products.RatingAndReviewModel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.CompanyModel'),
            preserve_default=False,
        ),
    ]
