# Generated by Django 2.1 on 2018-09-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_b_c'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C',
            new_name='People',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('products.people',),
        ),
    ]
