# Generated by Django 2.1 on 2018-09-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180906_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.CategoriesModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.CompanyModel'),
        ),
    ]
