# Generated by Django 2.1 on 2018-09-06 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180906_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='User_id',
            field=models.UUIDField(default=uuid.UUID('8512b769-0547-4950-b4dd-4a393b2226a5')),
        ),
    ]
