# Generated by Django 2.1 on 2018-09-07 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_newmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afield', models.CharField(max_length=5)),
                ('bfield', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='User_id',
            field=models.UUIDField(default=uuid.UUID('99677668-720b-4a6a-8cd8-d603e8fb3747')),
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('a_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.A')),
                ('cfield', models.CharField(max_length=5)),
            ],
            bases=('products.a',),
        ),
    ]
